### ISSUE TITLE
bug report nip46 login shows error "m.ZP.getSigner is not a function"

### ISSUE THREAD

**Issue by brugeman** [stackernews/stacker.news#1741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to use nip46 login (nip05 or bunker url) gives the same error "m.ZP.getSigner is not a function"

### Screenshots

![Screenshot from 2024-12-19 09-32-37](https://github.com/user-attachments/assets/c9a10553-5f51-4f1d-92a3-f0bbe3e72dd6)

### Steps To Reproduce

1. Go to Login with Nostr.
2. Type nip05 (i.e. artur@nsec.app) or a bunker url.
3. Click "Login with token or NIP05"
4. Error message

### Expected behavior

Expected behavior is for signer popup to show up so I could confirm the connection.

### Logs

hook.js:608 TypeError: m.ZP.getSigner is not a function
    at nostr-auth.js:128:28

Source code line referred above:
      const signer = Nostr.getSigner({ nip46token, supportNip07: useExtension })

### Device information

Ubuntu 20, Chrome 116

**Comment by ekzyis** [comment]
Oh sorry, I broke this in https://github.com/stackernews/stacker.news/pull/1739 trying to hotfix NWC zaps using the Alby relay. We will deploy the fix for this today!
